### ISSUE TITLE
ADB 820.00 broken

### ISSUE THREAD

**Issue by MttAI-dev** [AshamaneProject/AshamaneCore#185]
Guys there ADB_820.00 is broken and cant be loaded in to DB world. I was fixing it but there many entries templates and ect are missing. need fix it asap becose ppl using it atm and its really needed. trinity dont have custom scripts they use source but they don't have BFA respawn. also azerit power not working any ideas how to fix it?

**Comment by DJBoxer** [comment]
works perfect for me, tested and imported all DB including updates. 

Random guess is your issue is related to this https://github.com/AshamaneProject/AshamaneCore/issues/179#issuecomment-532734814

**Comment by MttAI-dev** [comment]
no, there is some misstakes on comas and dots and like creatyres table more then half is grey not in sql query, but just marked as text. before i did it was working last time i downloaded not working. okay i will try 1 more time to download it but i am not sure if it works.

**Comment by shamage** [comment]
the database is correct (except for the necessary modification [#179 (comment )](https://github.com/AshamaneProject/AshamaneCore/issues/179#issuecomment-532734814) ) 

I suggest to check if the database is really not damaged (full file)

**Comment by Gosa1979** [comment]
[SQL] Query ADB_world_820.00 start
[ERR] 5 - Out of memory (Needed 3053336 bytes)
[ERR] 
when i try to execute the sql

**Comment by buddyqc69** [comment]
You mysql server is enough memory for the drop files size

**Comment by Gosa1979** [comment]
> You mysql server is enough memory for the drop files size

what??
i dont understand

**Comment by Gosa1979** [comment]
srry got it im stupid nvm

**Comment by shamage** [comment]
> [SQL] Query ADB_world_820.00 start
> [ERR] 5 - Out of memory (Needed 3053336 bytes)
> [ERR]
> when i try to execute the sql

It sounds like to me Server is inadequate for the demand or severly misconfigured on this one.

**Comment by WinWoolF** [comment]
databases still cause installation errors. Someone found a way out of the situation?

**Comment by dio85** [comment]
The db update need full clean, if you put in the latest hotfix, the hotfix delete many table. and the update sql files, a littlebit outdted for 8.0 mysql. i mean if exists-> column if exists.  and have freezes in the core.

**Comment by WinWoolF** [comment]
I install a new repack and mysql bases are also installing new ones. It is not about updating an already running server.

**Comment by Daniel25** [comment]
Hello,I was wondering which is the way to install ashamanecore dbs. First I copy ADB 820.00 files in my server folder so it updates automatly and then....?It update the ashamene updates automatly too or I have to update ashamane updates mannually?I'm confuse with trinitycore autoupdate in ashamanecore....Sorry for asking it here,forum and website are down...Thanks you guys

**Comment by WinWoolF** [comment]
Daniel25 all updates should also be installed automatically. But for many, ADB 820.00 is not installed, progress simply does not reach updates.

**Comment by Daniel25** [comment]
Well I have installed the ADB 820 ok,I had to change max_allowed_packeds in the file ini of mysql to 500 MB (It was 4 MB). I'm figthing with the updates now :P.
I deleted 2019_06_08_00_characters.sql because both columns dont exists and it gives error.
2020_02_18_00_world.sql gives error because verifiedbuild colum is null in around of 350 rows,I created a fix adding a build in that rows.Checking if it finishs updating everything now...

**Comment by WinWoolF** [comment]
I changed the value of max_allowed_packeds at 5000m, now I also ran into an error with the update.
Applying of file 'C:/server/BFA/sql/ashamane/characters/2019_06_08_00_characters.sql' to database 'characters' failed!
Maybe you should try changing to 32000m)))

**Comment by Daniel25** [comment]
> I changed the value of max_allowed_packeds at 5000m, now I also ran into an error with the update.
> Applying of file 'C:/server/BFA/sql/ashamane/characters/2019_06_08_00_characters.sql' to database 'characters' failed!
> Maybe you should try changing to 32000m)))

With 500 It works for me ok. 
You can delete file,both columns are missing so you dont need to drop it. I have fixed every error with updatest. But I'm working in any error running worldserver because ashamane has missed any trinity's patches and there are any missing columns. 
Fixes for updates:

Delete parche 2019_06_08_00_characters.sql

add patch manually:
`UPDATE `creature_template_scaling`SET VerifiedBuild=0 WHERE `entry` IN(16345,
131089,16443,136945,140136,16357,127381,129788,126983,16250,15965,140149,16322,16323,
17655,129550,16601,16347,134572,15958,16274,134629,16339,139425,137204,133605,16327,136086,
131850,131677,135552,16245,126841,16199,129601,129599,130850,16337,136108,95204,135060,16238,
134990,134617,135846,126918,16198,16304,16353,16313,15409,129697,134025,135635,16348,135289,
136084,138762,135048,16252,16665,16200,129602,16293,129559,129547,138718,129527,129598,129600,
136087,129645,127106,16317,126969,16528,135987,130086,136154,16342,139108,15969,134616,15652,
134991,15655,133379,15668,139097,16318,16403,134691,129548,134686,134364,16319,134487,134599,
139422,135971,16331,137879,136696,131856,135624,136391,135562,15650,127480,16355,127485,135254,
135313,129437,16402,135553,131819,131585,16220,16343,137830,16202,131586,16542,131685,16344,16302,
130024,127119,16480,140138,129526,127352,16292,127315,128435,103785,107657,105938,107170,16239,16204,
130400,16295,16316,16310,16224,16335,15648,16219,16213,16340,16354,16330,137036,15420,100997,15670,15657,
15641,16196,15658,15636,15644,15402,16183,15945,15924,15645,15937,15966,16263,122971,15950,15642,127879,
133944,15408,16924,15949,15968,122969,134602,15647,16294,122973,122972,17210,128434,122984,17086,129553,
16464,15649,129552,128455,122963,125977,122965,122967,122968,16329,137233,131289,16231,16320,132126,128956,
16197,122970,16321,129517,16309,126734,125828,16246,16314,19456,16201,125868,16325,16311,130025,127503,
130087,135629,135341,136161,136085,136094,16352,138761,135556,135633,16463,131587,16315,16358,16341,17656,
131812,135240,135365,16334,16326,136330,134024,131670,131849,16332,16301,131669,16351,129732,129743,128551,
16303,130522,127124,126845,127111,126919,126928,126832,127757,130521,16162,130011,16308,16300,135989,16349,
112861,127799,130404,93679,107924,93654,109620,129529,107169,126848,112636,16291,16462,126847,16350,136539,
130012,16333,16205,129673,16253,16237,16324,16469,130902,122986,129699,130099,16346,138463,130172,130090,
16305,129448,134828,139970,129359,140144,15638,135816,129747,138705,130912,16328,15967,140145,140119,139300,
136406,134714,136408,139163,15643,143693,135445,135336,137857,136291,136407,17849,136404, 16203,15941,134600,
15407,15656,142929,15651,15637,15669);
`
before of patch 2020_02_18_00_world.sql or when you get error with that patch.

Comment-- ALTER TABLE `item_appearance` DROP COLUMN IF EXISTS `SubclassID`;
in patch  2020_02_17_00_hotfixes.sql,the column dont exist.

Change lines in 2020_02_18_00_hotfixes.sql  instead of modify,columns dont exist:

ALTER TABLE `artifact_tier` ADD `VerifiedBuild` int(11) NOT NULL DEFAULT '0' AFTER `MinimumEmpowerKnowledge`;

ALTER TABLE `artifact_unlock` ADD `VerifiedBuild` int(11) NOT NULL DEFAULT '0'AFTER `ArtifactID`;

**Comment by WinWoolF** [comment]
In the last half hour, I fixed or deleted many update files. But I keep getting errors. It breaks my brain ... Daniel25 if you have the strength and patience to figure it all out, could you make backups of the databases and post a link to download them. I and many others would be immensely grateful to you.

**Comment by Daniel25** [comment]
Sure m8,just in this moment i got everything ok and server is running good and updated ^^.
Beside of the steps which I commented up, you have to copy in ashamanecore/hotfixes the patch of update/hotfixes 2019_10_26_00_hotfixes,ashamanecore forgot to apply it. And everything will work ^^.
I will post here a link with the 4 dbs when I have uploaded it.

**Comment by WinWoolF** [comment]
respect my friend, you are a real gentleman!

**Comment by Daniel25** [comment]
https://mega.nz/file/jRpzgLpb#zbCct34DAePK3Y-9cG1rVlUi-LzooOo8LTkT66UtBnM 
That are the 4 dbs. I have renamed the dbs so you dont forget to change the name of dbs in bnetserver.config and worldserver.config so server can connect or you can change the name of db in every file changing line:

USE `auth_ashamanecore_bfa`;
for
USE `your db name`;
;)

**Comment by WinWoolF** [comment]
Thanks! This is a great job!

**Comment by firelook** [comment]
your database should be used as 8.3 !!! ;)

**Comment by Daniel25** [comment]
> your database should be used as 8.3 !!! ;)

It isnt bad idea :P.I will check a thing and  if it is ok I will try to create a pull request so fixes are added in ashamanecore :).
Edited: pull request done,while ashamanecore check it you can use my repository https://github.com/Daniel25/AshamaneCore with every db thing fixed,it compiles good and dbs update ok too. For more info about instaling it you can check my youtube chanel video ^^ : https://www.youtube.com/watch?v=f9SMUi_gE5Q

**Comment by mcsescott** [comment]
Thank you for your work, Daniel25.

**Comment by Daniel25** [comment]
solved / integrated in latest commit

**Comment by Traesh** [comment]
Closed by @Daniel25 PR (thx)
