### ISSUE TITLE
ADB Errors

### ISSUE THREAD

**Issue by Grimmy347** [AshamaneProject/AshamaneCore#189]
Is it normal to have tons of errors when launching the world server with the most up to date adb and current core?

**Comment by DJBoxer** [comment]
yes, for many reasons but main one being missing scripts or no SQL Data for newer content or newer expansions break past data. That's why most make wotlk and past expansions live servers as it has a more stable structure compared to recent expansions. 

Either way this is not really a reason for your issue created, as this can be answered on a forum or discord. Otherwise add your logs and crash reports and then wait for a fix or PR.
