### ISSUE TITLE
[1146] Table 'world.updates_include' doesn't exist Your database structure is not up to date. Please make sure you've executed all queries in the sql/updates folders.

### ISSUE THREAD

**Issue by 790113822** [AshamaneProject/AshamaneCore#270]
[1146] Table 'world.updates_include' doesn't exist
Your database structure is not up to date. Please make sure you've executed all queries in the sql/updates folders.

我已经确认我的sql/updates为最新，因为我的源码几天前才下载的。我需要帮助。

google translation：
I have confirmed that my sql/updates is up to date because my source code was downloaded only a few days ago. I need help.

**Comment by DuelistRag3** [comment]
I've seen this error happened quiet often, but I can't recreate it at the moment, I will investigate it later or tomorrow, for now, you can just create the table manually, you can check the Auth database, to get the structure of the table, both "updates" and "updates_include" are existing also there

**Comment by Hooaah** [comment]
Did you rename  world database from ashamane-world to just world  it will cause two different world schemas on your server, same for hotfixes database

**Comment by alexyang-sea** [comment]
I also encountered this problem, finally asked for advice, told me to import the ahbot database, I imported, and no problem, if you have ahbot module, you can also try.

**Comment by xXRaptorSc0pezXx** [comment]
To fix the problem just go to HeidiSQL --> File --> Run SQL file... --> navigate to \azerothcore-wotlk\modules\mod-playerbots\mod-playerbots\data\sql\world\base and manually run each of the files in there to create the tables since it doesn't do it automatically for some reason.

If you are trying to install the Azerothcore Playerbots branch without the Playerbots module added to the Azerothcore folder you will need to clone that repository first (clone it to \azerothcore-wotlk\modules\mod-playerbots\ keep in mind you will need to create the "mod-playerbots folder").
