### ISSUE TITLE
Some Crashdumps

### ISSUE THREAD

**Issue by darkmord1991** [AshamaneProject/AshamaneCore#386]
**Description:**
Here are some Crashdumps, maybe they help you.

Or should I compile with debug?

**Usefull Wowhead links:**

[Crashes.zip](https://github.com/AshamaneProject/AshamaneCore/files/1628207/Crashes.zip)

**Comment by Nexon99** [comment]
Thanks.

**Comment by Traesh** [comment]
Yup those are currently useless, you should compile in debug to have verbose crashlogs

Thanks

**Comment by darkmord1991** [comment]
debug or release with debug info?

**Comment by Traesh** [comment]
Any

Le 13 janv. 2018 12:58 PM, "darkmord1991" <notifications@github.com> a
écrit :

debug or release with debug info?

—
You are receiving this because you were assigned.

Reply to this email directly, view it on GitHub
<https://github.com/AshamaneProject/AshamaneCore/issues/386#issuecomment-357429630>,
or mute the thread

**Comment by darkmord1991** [comment]
thx, i will compile and upload the crashdumps again
