### ISSUE TITLE
Character Creation Limit

### ISSUE THREAD

**Issue by Neredun** [AshamaneProject/AshamaneCore#791]
**Description:**
On live server i saw that i can only create 12 Characters instead of 16. I remember that a commit was added regarding this but it seems that it didn't get apply on live realm. (this one: https://github.com/AshamaneProject/AshamaneCore/commit/1b8f791846f337c6caa8e6268754b9cbed52c0be also i saw another who didn't get apply which changes build versions so it wouldn't be the only one. Maybe this is intended?)

**Comment by lorac2k14** [comment]
I can personally say as of 10 minutes ago you can roll 16 toons on a retail account with pre-purchase of BFA and with the release of allied races. so 16 characters is valid. besides if it was not accepted by client it would crash due to client limitations as the client will more than likely check the db2 data

**Comment by Neredun** [comment]
i'm not sure if i was mistaken. But with Live Server i was refering to Ashamane Private Server, not Retail. Anyway it shouldn't be problems with the client limitation. Because to have the Allied Races available we need to have the Expansion set as 7 (BfA) so we are already marked as "BfA accounts" and we even have access to the "create new character" option, but it always appear the message regarding character limits on the realm. (like happened before when Death Knight was limited to 1 per realm)

**Comment by Traesh** [comment]
Fixed
