### ISSUE TITLE
Moonfire Quest is Obsolete

### ISSUE THREAD

**Issue by Ysil69** [AshamaneProject/AshamaneCore#870]
**Description:**
Quest is no longer around
14283 - Moonfire
26948 - Moonfire
27067 - Moonfire
**Usefull Wowhead links:**
http://www.wowhead.com/quest=27067/moonfire

**Comment by TheXWolf** [comment]
Ran this on my database a while back;
`DELETE FROM `quest_template` WHERE `Id` in (14283, 26948, 27067);
DELETE FROM `creature_queststarter` WHERE `quest` in (14283, 26948, 27067);
DELETE FROM `gameobject_queststarter` WHERE `quest` in (14283, 26948, 27067);
DELETE FROM `creature_questender` WHERE `quest` in (14283, 26948, 27067);
DELETE FROM `gameobject_questender` WHERE `quest` in (14283, 26948, 27067);
DELETE FROM `areatrigger_involvedrelation` WHERE `quest` in (14283, 26948, 27067);`

**Comment by HannibalRoG** [comment]
@TheXWolf use disable table dont delete from template

**Comment by TheXWolf** [comment]
Is there a particular reason? Leaving unused data in a database not only bloats it, but you then you don't know what's connected by lack of errors and silent failures. Is it just a preference or something ashamane does?

**Comment by Neredun** [comment]
@TheXWolf to start: that is something that even TC doesn't do. We avoid deleting things from _template tables mostly because it's more simple to keep it. Deleting it would most of the times result on errors because of missing data. Quests also uses data from other tables (like quest_objectives, quest_detail, quest_request_items...) so it's more easy, simple and less tedious. Also sometimes blizzard reuse things (most new example would be the New Racial Leader Saurfang, which uses an old NPC id 14720, of course he was updated). And for last: please, check before using delete froms. You literally could reduce your work checking on wowhead if the queststarter and enders is/was a creature, a gameobject or an areatrigger.

**Comment by TheXWolf** [comment]
@Neredun I totally understand that, and to some degree it makes sense. Except for the fact blizzard doesn't reuse quest IDs, once they're marked deprecated it's unlikely they're ever seen again. My only idea is, you say it's easier; but if you leave a quest ID, it's not coming back, and unless you removed it properly(i.e. everything connected to it)...now you'll get errors (which help you remove everything) and keep the size of the db down. If that's not a concern to anyone, then disable is fine, was only giving my 2c as a professional who's been told more than once never to do that kind-of thing. lol
