### ISSUE TITLE
DB/SQL: Deprecated class quests removed.

### ISSUE THREAD

**Issue by TheXWolf** [AshamaneProject/AshamaneCore#898]
Ran into 8 other quests I know to no longer be active in the game:
```sql
DELETE FROM `quest_template` WHERE `Id` in (31170, 8329, 27091, 10068, 10069, 10071, 10072, 10073);
DELETE FROM `creature_queststarter` WHERE `quest` in (31170, 8329, 27091, 10068, 10069, 10071, 10072, 10073);
DELETE FROM `gameobject_queststarter` WHERE `quest` in (31170, 8329, 27091, 10068, 10069, 10071, 10072, 10073);
DELETE FROM `creature_questender` WHERE `quest` in (31170, 8329, 27091, 10068, 10069, 10071, 10072, 10073);
DELETE FROM `gameobject_questender` WHERE `quest` in (31170, 8329, 27091, 10068, 10069, 10071, 10072, 10073);
DELETE FROM `areatrigger_involvedrelation` WHERE `quest` in (31170, 8329, 27091, 10068, 10069, 10071, 10072, 10073);
```

**Comment by Traesh** [comment]
Thanks you for the requests, just two minors things

1) could you please also check that no quest depend of these ones ? Example, check that no quest have PreviousQuestId = 31170 (and if yes, replace it with correct value)
2) Could you please use disable table instead of delete from quest_template ?

**Comment by Neredun** [comment]
@Traesh I decided to take care of this. 

 I also added some missing quests that are missing in this patch (the "<Class> Training" that are before the practice <spell>) also there's no need to change PrevQuestId or NextQuestId since there only quests that are set are the <Class> Training to > Practice Spell Quest and Viceversa, so it doesn't make problems. Also i delete questgivers flags and changed other deprecated quests (but not marked as obsolete) to do a complete work on Sunstrider Isle.

[Sunstrider Isle.zip](https://github.com/AshamaneProject/AshamaneCore/files/1935371/Sunstrider.Isle.zip)
